name: Swift Package Build and Tests

on: [push, pull_request]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: find . -name "Package.swift" -execdir swift build \;
      - name: Run tests
        run: find . -name "Package.swift" -execdir swift test \;
